"""adding song models

Revision ID: 2118701794a2
Revises: 7726828eb595
Create Date: 2025-09-27 15:39:44.960022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2118701794a2'
down_revision: Union[str, Sequence[str], None] = '7726828eb595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('LOCAL', 'SPOTIFY', 'YOUTUBE', name='songsource'), nullable=False),
    sa.Column('uri', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('album', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('play_count', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('last_played', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_song')),
    sa.UniqueConstraint('uri', name=op.f('uq_song_uri'))
    )
    op.create_table('playlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('MANUAL', 'SMART', 'IMAGE', name='playlisttype'), nullable=False),
    sa.Column('query', sa.JSON(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], name=op.f('fk_playlist_image_id_image'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_playlist'))
    )
    op.create_table('song_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], name=op.f('fk_song_tag_song_id_song'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_song_tag_tag_id_tag'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_song_tag')),
    sa.UniqueConstraint('song_id', 'tag_id', name='uq_song_tag_song_tag')
    )
    with op.batch_alter_table('song_tag', schema=None) as batch_op:
        batch_op.create_index('ix_song_tag_song_id', ['song_id'], unique=False)
        batch_op.create_index('ix_song_tag_tag_id', ['tag_id'], unique=False)

    op.create_table('playlist_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], name=op.f('fk_playlist_item_playlist_id_playlist'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], name=op.f('fk_playlist_item_song_id_song'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_playlist_item'))
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('playlist_item')
    with op.batch_alter_table('song_tag', schema=None) as batch_op:
        batch_op.drop_index('ix_song_tag_tag_id')
        batch_op.drop_index('ix_song_tag_song_id')

    op.drop_table('song_tag')
    op.drop_table('playlist')
    op.drop_table('song')
    # ### end Alembic commands ###
