"""adding schema

Revision ID: d22d96ec48ce
Revises: e197f5a5df00
Create Date: 2025-09-17 10:52:40.165315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd22d96ec48ce'
down_revision: Union[str, Sequence[str], None] = 'e197f5a5df00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.String(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['folder.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'name', name='uq_folder_parent_name')
    )
    op.create_index('idx_folder_parent', 'folder', ['parent_id'], unique=False)
    op.create_index('idx_folder_parent_pos', 'folder', ['parent_id', 'position'], unique=False)
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('hash_sha256', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('width_px', sa.Integer(), nullable=True),
    sa.Column('height_px', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('bytes_size', sa.Integer(), nullable=True),
    sa.Column('taken_at', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('meta_json', sa.JSON(), nullable=True),
    sa.Column('has_data', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.String(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash_sha256')
    )
    op.create_index('idx_image_uri', 'image', ['uri'], unique=False)
    op.create_table('album',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('color_hint', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.String(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folder_id', 'name', name='uq_album_folder_name')
    )
    op.create_index('idx_album_folder', 'album', ['folder_id'], unique=False)
    op.create_index('idx_album_folder_pos', 'album', ['folder_id', 'position'], unique=False)
    op.create_table('image_data',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('bytes', sa.LargeBinary(), nullable=False),
    sa.Column('thumb_bytes', sa.LargeBinary(), nullable=True),
    sa.Column('bytes_format', sa.String(), nullable=True),
    sa.Column('thumb_format', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_table('album_image',
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.String(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('album_id', 'image_id')
    )
    op.create_index('idx_collimg_album_pos', 'album_image', ['album_id', 'position'], unique=False)
    op.create_index('idx_collimg_image', 'album_image', ['image_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_collimg_image', table_name='album_image')
    op.drop_index('idx_collimg_album_pos', table_name='album_image')
    op.drop_table('album_image')
    op.drop_table('image_data')
    op.drop_index('idx_album_folder_pos', table_name='album')
    op.drop_index('idx_album_folder', table_name='album')
    op.drop_table('album')
    op.drop_index('idx_image_uri', table_name='image')
    op.drop_table('image')
    op.drop_index('idx_folder_parent_pos', table_name='folder')
    op.drop_index('idx_folder_parent', table_name='folder')
    op.drop_table('folder')
    # ### end Alembic commands ###
