"""initial schema

Revision ID: 52501f8d626b
Revises: 
Create Date: 2025-09-17 11:38:35.416636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52501f8d626b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.String(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['folder.id'], name=op.f('fk_folder_parent_id_folder'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_folder')),
    sa.UniqueConstraint('parent_id', 'name', name='uq_folder_parent_name')
    )
    with op.batch_alter_table('folder', schema=None) as batch_op:
        batch_op.create_index('idx_folder_parent', ['parent_id'], unique=False)
        batch_op.create_index('idx_folder_parent_pos', ['parent_id', 'position'], unique=False)

    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('hash_sha256', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('width_px', sa.Integer(), nullable=True),
    sa.Column('height_px', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('bytes_size', sa.Integer(), nullable=True),
    sa.Column('taken_at', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('meta_json', sa.JSON(), nullable=True),
    sa.Column('has_data', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.String(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_image')),
    sa.UniqueConstraint('hash_sha256', name=op.f('uq_image_hash_sha256'))
    )
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.create_index('idx_image_uri', ['uri'], unique=False)

    op.create_table('album',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('color_hint', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.String(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['folder.id'], name=op.f('fk_album_parent_id_folder'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_album')),
    sa.UniqueConstraint('parent_id', 'name', name='uq_album_parent_id_name')
    )
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.create_index('idx_album_folder', ['parent_id'], unique=False)
        batch_op.create_index('idx_album_folder_pos', ['parent_id', 'position'], unique=False)

    op.create_table('image_data',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('bytes', sa.LargeBinary(), nullable=False),
    sa.Column('thumb_bytes', sa.LargeBinary(), nullable=True),
    sa.Column('bytes_format', sa.String(), nullable=True),
    sa.Column('thumb_format', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], name=op.f('fk_image_data_image_id_image'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id', name=op.f('pk_image_data'))
    )
    op.create_table('album_image',
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.String(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], name=op.f('fk_album_image_album_id_album'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], name=op.f('fk_album_image_image_id_image'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('album_id', 'image_id', name=op.f('pk_album_image'))
    )
    with op.batch_alter_table('album_image', schema=None) as batch_op:
        batch_op.create_index('idx_collimg_album_pos', ['album_id', 'position'], unique=False)
        batch_op.create_index('idx_collimg_image', ['image_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album_image', schema=None) as batch_op:
        batch_op.drop_index('idx_collimg_image')
        batch_op.drop_index('idx_collimg_album_pos')

    op.drop_table('album_image')
    op.drop_table('image_data')
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.drop_index('idx_album_folder_pos')
        batch_op.drop_index('idx_album_folder')

    op.drop_table('album')
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_index('idx_image_uri')

    op.drop_table('image')
    with op.batch_alter_table('folder', schema=None) as batch_op:
        batch_op.drop_index('idx_folder_parent_pos')
        batch_op.drop_index('idx_folder_parent')

    op.drop_table('folder')
    # ### end Alembic commands ###
