name: Build & attach assets (after version bump)

on:
  workflow_run:
    workflows: ["Version bump (semantic-release)"]
    types: [completed]
    branches: [main]

permissions:
  contents: write
  actions: read

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: { os: [ubuntu-latest, windows-latest] }

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      # Pull the artifact from the previous workflow run
      - name: Download version metadata
        uses: actions/download-artifact@v4
        with:
          name: version-meta
          path: meta
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}

      - name: Read tag/sha
        id: meta
        shell: bash
        run: |
          echo "tag=$(cat meta/tag.txt)" >> "$GITHUB_OUTPUT"
          echo "sha=$(cat meta/sha.txt)" >> "$GITHUB_OUTPUT"

      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
          python -m pip install pyinstaller

      - name: Build (PyInstaller)
        run: python -m PyInstaller "GM Assistant.spec"

      # rename to unique, OS-specific + versioned names
      - name: Name artifact (Linux)
        if: runner.os == 'Linux'
        shell: bash
        run: |
          VER="${{ steps.meta.outputs.tag }}"; VER="${VER#v}"
          SRC="dist/GM Assistant"; [ -f "$SRC" ] || SRC="$(find dist -maxdepth 1 -type f -print -quit)"
          DEST="GM-Assistant-${VER}-linux"
          mv "$SRC" "$DEST"
          echo "ARTIFACT=$DEST" >> "$GITHUB_ENV"

      - name: Name artifact (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $ver = "${{ steps.meta.outputs.tag }}".TrimStart("v")
          $src = Join-Path dist 'GM Assistant.exe'
          if (-not (Test-Path $src)) { $src = (Get-ChildItem dist -Filter *.exe | Select-Object -First 1).FullName }
          $dest = "GM-Assistant-$ver-windows.exe"
          Move-Item $src $dest -Force
          "ARTIFACT=$dest" >> $env:GITHUB_ENV

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-assets-${{ matrix.os }}
          path: ${{ env.ARTIFACT }}

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      # download both OS artifacts
      - uses: actions/download-artifact@v4
        with:
          name: release-assets-ubuntu-latest
          path: dist
      - uses: actions/download-artifact@v4
        with:
          name: release-assets-windows-latest
          path: dist

      # get tag from upstream version job
      - uses: actions/download-artifact@v4
        with:
          name: version-meta
          path: meta
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
      - id: meta
        shell: bash
        run: echo "tag=$(cat meta/tag.txt)" >> "$GITHUB_OUTPUT"

      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: pip install python-semantic-release

      - name: Publish to the Release
        run: semantic-release -vv publish --tag "${{ steps.meta.outputs.tag }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
